name: bauhaus
services:
  bauhaus-back:
    extends:
      file: compose/bauhaus-back.yaml
      service: bauhaus-back
    links:
      - graphdb

  graphdb:
    extends:
      file: compose/graphdb.yaml
      service: graphdb